<?php
// Register Custom Post Type footer brand
function mobile_ecommerce_post()
{

   $labels_footer_brands = array(
      'name'                  => _x('Footer Brands', 'Post Type General Name', 'mobileecom'),
      'singular_name'         => _x('Brand', 'Post Type Singular Name', 'mobileecom'),
      'menu_name'             => __('Footer Brands', 'mobileecom'),
      'name_admin_bar'        => __('Brands', 'mobileecom'),
      'archives'              => __('Item Archives', 'mobileecom'),
      'attributes'            => __('Item Attributes', 'mobileecom'),
      'parent_item_colon'     => __('Parent Item:', 'mobileecom'),
      'all_items'             => __('All Items', 'mobileecom'),
      'add_new_item'          => __('Add New Item', 'mobileecom'),
      'add_new'               => __('Add New', 'mobileecom'),
      'new_item'              => __('New Item', 'mobileecom'),
      'edit_item'             => __('Edit Item', 'mobileecom'),
      'update_item'           => __('Update Item', 'mobileecom'),
      'view_item'             => __('View Item', 'mobileecom'),
      'view_items'            => __('View Items', 'mobileecom'),
      'search_items'          => __('Search Item', 'mobileecom'),
      'not_found'             => __('Not found', 'mobileecom'),
      'not_found_in_trash'    => __('Not found in Trash', 'mobileecom'),
      'featured_image'        => __('Featured Image', 'mobileecom'),
      'set_featured_image'    => __('Set featured image', 'mobileecom'),
      'remove_featured_image' => __('Remove featured image', 'mobileecom'),
      'use_featured_image'    => __('Use as featured image', 'mobileecom'),
      'insert_into_item'      => __('Insert into item', 'mobileecom'),
      'uploaded_to_this_item' => __('Uploaded to this item', 'mobileecom'),
      'items_list'            => __('Items list', 'mobileecom'),
      'items_list_navigation' => __('Items list navigation', 'mobileecom'),
      'filter_items_list'     => __('Filter items list', 'mobileecom'),
   );
   $footer_brands_args = array(
      'label'                 => __('Footer Brand', 'mobileecom'),
      'description'           => __('Give brand image', 'mobileecom'),
      'labels'                => $labels_footer_brands,
      'supports'              => array('title', 'thumbnail'),
      'hierarchical'          => false,
      'public'                => true,
      'show_ui'               => true,
      'show_in_menu'          => true,
      // 'menu_position'         => 5,
      'show_in_admin_bar'     => true,
      'show_in_nav_menus'     => true,
      'can_export'            => true,
      'has_archive'           => true,
      'exclude_from_search'   => false,
      'publicly_queryable'    => true,
      'capability_type'       => 'page',
   );

   // Register Custom Post Type footer feature
   $label_footer_features  = array(
      'name'                  => _x('Features', 'Post Type General Name', 'mobileecom'),
      'singular_name'         => _x('Feature', 'Post Type Singular Name', 'mobileecom'),
      'menu_name'             => __('Features', 'mobileecom'),
      'name_admin_bar'        => __('Features', 'mobileecom'),
      'archives'              => __('Item Archives', 'mobileecom'),
      'attributes'            => __('Item Attributes', 'mobileecom'),
      'parent_item_colon'     => __('Parent Item:', 'mobileecom'),
      'all_items'             => __('All Items', 'mobileecom'),
      'add_new_item'          => __('Add New Item', 'mobileecom'),
      'add_new'               => __('Add New', 'mobileecom'),
      'new_item'              => __('New Item', 'mobileecom'),
      'edit_item'             => __('Edit Item', 'mobileecom'),
      'update_item'           => __('Update Item', 'mobileecom'),
      'view_item'             => __('View Item', 'mobileecom'),
      'view_items'            => __('View Items', 'mobileecom'),
      'search_items'          => __('Search Item', 'mobileecom'),
      'not_found'             => __('Not found', 'mobileecom'),
      'not_found_in_trash'    => __('Not found in Trash', 'mobileecom'),
      'featured_image'        => __('Featured Image', 'mobileecom'),
      'set_featured_image'    => __('Set featured image', 'mobileecom'),
      'remove_featured_image' => __('Remove featured image', 'mobileecom'),
      'use_featured_image'    => __('Use as featured image', 'mobileecom'),
      'insert_into_item'      => __('Insert into item', 'mobileecom'),
      'uploaded_to_this_item' => __('Uploaded to this item', 'mobileecom'),
      'items_list'            => __('Items list', 'mobileecom'),
      'items_list_navigation' => __('Items list navigation', 'mobileecom'),
      'filter_items_list'     => __('Filter items list', 'mobileecom'),
   );
   $args_footer_features = array(
      'label'                 => __('Footer Feature', 'mobileecom'),
      'description'           => __('Give feature image', 'mobileecom'),
      'labels'                =>  $label_footer_features,
      'supports'              => array('title', 'editor', 'thumbnail'),
      'hierarchical'          => false,
      'public'                => true,
      'show_ui'               => true,
      'show_in_menu'          => true,
      // 'menu_position'         => 5,
      'show_in_admin_bar'     => true,
      'show_in_nav_menus'     => true,
      'can_export'            => true,
      'has_archive'           => true,
      'exclude_from_search'   => false,
      'publicly_queryable'    => true,
      'capability_type'       => 'page',
   );
   register_post_type('footer_brand', $footer_brands_args);
   register_post_type('footer_our_features', $args_footer_features);
}
add_action('init', 'mobile_ecommerce_post', 0);
